version: '3.8'

services:

  db:
    env_file:
      - .env
    
    image: postgres
    restart: always
    ports:
      - "5432:5432"

  todo-api:
    env_file:
      - .env

    image: safeshare/api
    restart: always
    depends_on:
      - db
    #      - localstack-s3
    links:
      - db:${POSTGRES_SERVER_ALIAS}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
  
  minio:
    image: minio/minio
    hostname: ${MINIO_CONTAINER_NAME}
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    ports:
      - "${MINIO_API_PORT}:${MINIO_API_PORT}"
      - "9090:9090"
    volumes:
      - ~/minio/data:/data
    command: "server /data --console-address :9090"
